### ISSUE TITLE
Update package_data urls for rh7.

### ISSUE THREAD

**Issue by mdickinson** [enthought/setup-edm-action#6]
The current package_data url hard-codes `rh6`, but it appears that recent installers live under `rh7`.

**Comment by mdickinson** [comment]
This affects EDM 3.4.0 (and probably any later versions, too).

**Comment by beftekhari** [comment]
My team encountered this with 3.4.0. The setup-edm-action itself does not return any errors:
```
Run enthought/setup-edm-action@v1
  with:
    edm-version: 3.4.0
    download-directory: ~/.cache/download
  env:
    INSTALL_EDM_VERSION: 3.4.0
    HATCHER_TOKEN: ***
Using directory for storing downloaded installer: /home/runner/.cache/download
/usr/bin/bash /home/runner/work/_actions/enthought/setup-edm-action/v1/dist/install-edm-linux.sh 3.4.0 /home/runner/.cache/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   55    0   255    0     0    847      0 --:--:-- --:--:-- --:--:--   847
/home/runner/.cache/download/edm_cli_3.4.0_linux_x86_64.sh: line 1: syntax error near unexpected token `newline'
/home/runner/.cache/download/edm_cli_3.4.0_linux_x86_64.sh: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
(node:2120) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/bash' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1026:2)
    at ExecState.CheckComplete (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1009:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:903:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:1)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:65:12)
(node:2120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2120) [DEP001] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Attempting to use edm in a later action does:
```
Run edm --config ci/data/edm.yaml --api-token $HATCHER_TOKEN install --version 3.6 -y -e bootstrap click setuptools pyyaml
/home/runner/work/_temp/0b52d5e-44f0-410c-9eb6-47cffaf91e3.sh: line 1: edm: command not found
Error: Process completed with exit code 127.
```

**Comment by mdickinson** [comment]
> The setup-edm-action itself does not return any errors

Yep, this part is #3.

**Comment by mdickinson** [comment]
> but it appears that recent installers live under `rh7`

This may not be right. Simply substituting `rh7` for `rh6` in the expected path isn't working for me. We need to get information about the correct URL from the EDM team.

**Comment by mdickinson** [comment]
The issue was that the EDM installers hadn't been uploaded to the appropriate place; that's now fixed.

**Comment by mdickinson** [comment]
I opened enthought/envisage#484 to double check the fix. It appears to be working as expected. E.g.: https://github.com/enthought/envisage/actions/runs/3043073435/
